/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LocationsRealWorldImport } from './routes/locations/real-world'
import { Route as LocationsAbstractImport } from './routes/locations/abstract'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocationsRealWorldRoute = LocationsRealWorldImport.update({
  id: '/locations/real-world',
  path: '/locations/real-world',
  getParentRoute: () => rootRoute,
} as any)

const LocationsAbstractRoute = LocationsAbstractImport.update({
  id: '/locations/abstract',
  path: '/locations/abstract',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/locations/abstract': {
      id: '/locations/abstract'
      path: '/locations/abstract'
      fullPath: '/locations/abstract'
      preLoaderRoute: typeof LocationsAbstractImport
      parentRoute: typeof rootRoute
    }
    '/locations/real-world': {
      id: '/locations/real-world'
      path: '/locations/real-world'
      fullPath: '/locations/real-world'
      preLoaderRoute: typeof LocationsRealWorldImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locations/abstract': typeof LocationsAbstractRoute
  '/locations/real-world': typeof LocationsRealWorldRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locations/abstract': typeof LocationsAbstractRoute
  '/locations/real-world': typeof LocationsRealWorldRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/locations/abstract': typeof LocationsAbstractRoute
  '/locations/real-world': typeof LocationsRealWorldRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/locations/abstract' | '/locations/real-world'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/locations/abstract' | '/locations/real-world'
  id: '__root__' | '/' | '/locations/abstract' | '/locations/real-world'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationsAbstractRoute: typeof LocationsAbstractRoute
  LocationsRealWorldRoute: typeof LocationsRealWorldRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationsAbstractRoute: LocationsAbstractRoute,
  LocationsRealWorldRoute: LocationsRealWorldRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/locations/abstract",
        "/locations/real-world"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/locations/abstract": {
      "filePath": "locations/abstract.tsx"
    },
    "/locations/real-world": {
      "filePath": "locations/real-world.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
